# Generated by Django 5.0.1 on 2024-01-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="customer",),
        migrations.RemoveField(model_name="shipment", name="name",),
        migrations.RemoveField(model_name="shipment", name="shipment_date",),
        migrations.AddField(
            model_name="shipment",
            name="destination",
            field=models.CharField(default="Default Destination", max_length=100),
        ),
        migrations.AddField(
            model_name="shipment", name="weight", field=models.FloatField(default=100),
        ),
        migrations.DeleteModel(name="Customer",),
    ]
