# Generated by Django 5.0.1 on 2024-01-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0002_remove_shipment_customer_remove_shipment_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="shipment", name="destination",),
        migrations.AddField(
            model_name="shipment",
            name="from_city",
            field=models.CharField(
                choices=[("city1", "City 1"), ("city2", "City 2"), ("city3", "City 3")],
                default="city1",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shipment_date",
            field=models.DateField(default="2024-01-01"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="to_city",
            field=models.CharField(
                choices=[("city1", "City 1"), ("city2", "City 2"), ("city3", "City 3")],
                default="city1",
                max_length=100,
            ),
        ),
    ]
