# Generated by Django 5.0.1 on 2024-01-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipment", "0003_remove_shipment_destination_shipment_from_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="from_city",
            field=models.CharField(
                choices=[("Amman", "Amman"), ("Irbid", "Irbid"), ("Aqaba", "Aqaba")],
                default="Amman",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="to_city",
            field=models.CharField(
                choices=[("Aqaba", "Aqaba"), ("Amman", "Amman"), ("Irbid", "Irbid")],
                default="Aqaba",
                max_length=100,
            ),
        ),
    ]
